### ISSUE TITLE
Add Snake Game Using HTML, CSS, and JavaScript as 26th Project

### ISSUE THREAD

**Issue by Kaustav2410** [dhairyagothi/100_days_100_web_project#10]
I propose adding a new project to the repository: a classic Snake game implemented using HTML, CSS, and JavaScript. This will be the 26th project and will serve as a fun and educational exercise for those learning web development.

**Comment by dhairyagothi** [comment]
Good to go @Kaustav2410 

Please star ⭐ the repo and add files in a seperate folder and also update index. html file so that it can serve directly to main website 

Assigned @Kaustav2410 

Go ahead

**Comment by dhairyagothi** [comment]
completed #24
