### ISSUE TITLE
Implement Netflix Clone

### ISSUE THREAD

**Issue by Yaser-123** [dhairyagothi/100_days_100_web_project#102]
The goal of this project is to create a functional clone of the Netflix platform. This clone should mimic the core features of Netflix, including user authentication, browsing of movie/TV show catalogs, streaming video content, and user-specific recommendations.

Key Features:
1.Header Section
2.Hero Section
3.Content Sections
4.Footer Section

Technical Stack:
1.Frontend
2.Responsive Design
3.Consistent Theme

Additional Notes:
Collaborate with the design team to ensure visual fidelity.
Ensure cross-browser compatibility (Chrome, Firefox, Safari, Edge).
Solicit feedback from team members and potential users to refine the design.

Netflix for Laptops (Big Screen devices):-

https://github.com/dhairyagothi/50_days_50_web_project/assets/140265777/62e075b0-bd3a-4a62-b8db-c1b3b40c2387

Netflix for Mobiles (Small screen devices) :-

https://github.com/dhairyagothi/50_days_50_web_project/assets/140265777/e2679cc7-884f-4ac4-8106-05f2a46c550c

**Comment by dhairyagothi** [comment]
okay add it @Yaser-123
