### ISSUE TITLE
Snake Game Using HTML,CSS,JS

### ISSUE THREAD

**Issue by MonishRaman** [dhairyagothi/100_days_100_web_project#103]
In this we have sound features and u can feel the real game vibe

So I would like to add some Background realistic sounds and background

**Comment by dhairyagothi** [comment]
Already there check live link @MonishRaman

**Comment by MonishRaman** [comment]
ya but this is new model

**Comment by MonishRaman** [comment]
https://github.com/dhairyagothi/50_days_50_web_project/assets/140420819/17fd9f0f-efaa-4257-bf97-61411cb4418a
