### ISSUE TITLE
Ping Pong Ball Game

### ISSUE THREAD

**Issue by MonishRaman** [dhairyagothi/100_days_100_web_project#109]
**Ping Pong Ball Score-Keeper**

- Project Overview

In this project user can keep score of various 2 players games. The maximum score can be 11 and score is reset after every game.The buttons turn red and green for winner and loser respectively. After the winning the game the score can not be increased.

- Use Of the Project

User can keep score of their games.

- Languages Used

HTML
CSS
Javascript

- How to Use

1. Using the project is very easy.
2. First select the maximum Score/Wining Score.
3. To increase the score of player 1 by pressing player-1 button and increase the score of player 2 by pressing player-2 button.
4. After reaching the maximum score winner would be declared by an alert message and green color of button and score.
5. To play another game press reset button and choose your winning score.

- Sample Pictures

![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/140420819/cab1e9af-a7cb-4bdb-ab60-8f3406fce859)
Opening Page

![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/140420819/4f5b5c6d-7625-4055-9279-26955c1ac9e6)

counting page

![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/140420819/6db0658f-29b4-4c8f-92a0-0f08f095b8ba)

player1 wins

![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/140420819/c94b2e98-be35-4756-92d2-6738d4066c78)

game is reset

**Comment by dhairyagothi** [comment]
Assigned @MonishRaman
