### ISSUE TITLE
Text to Voice Converter

### ISSUE THREAD

**Issue by Umashankar08** [dhairyagothi/100_days_100_web_project#110]
Implementing Text to voice converter using Html,Css,Js. A text-to-voice converter is an application or tool that converts written text into spoken audio. It utilizes text-to-speech (TTS) technology to generate human-like speech from input text, enabling users to listen to written content instead of reading it.

**Comment by dhairyagothi** [comment]
Okay go ahead @Umashankar08 
Assigned 
Read contribution.md before starting

**Comment by Umashankar08** [comment]
![Screenshot 2024-06-20 165155](https://github.com/dhairyagothi/50_days_50_web_project/assets/143025358/e4e08eae-c709-4b29-b8f3-aebd50aa9007)
I have done this..Is it okay

**Comment by Umashankar08** [comment]
Can i proceed??

**Comment by dhairyagothi** [comment]
make a PR @Umashankar08
