### ISSUE TITLE
Tic tac toe new game issue

### ISSUE THREAD

**Issue by k0msenapati** [dhairyagothi/100_days_100_web_project#115]
**Describe the bug**

**To Reproduce**
1. Go to ['...'](https://50-days-50-web-project.vercel.app/TicTacToe/index.html)
2. Complete the game
3. Click 'New game'

**Expected behavior**
A new game will start!

**Screenshots**
![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/92045934/fbcd9982-6532-4f30-a1e7-65adbfa106cc)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version latest

**Comment by dhairyagothi** [comment]
ok fix it @kom-senapati
