### ISSUE TITLE
Enhancing To-Do List Functionality with PDF Export and Document Management

### ISSUE THREAD

**Issue by atharva012004** [dhairyagothi/100_days_100_web_project#116]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to keep track of my to-do list outside of the application. Having to manually copy items to another format or document to share, save, or archive them is time-consuming and prone to errors. Additionally, there is no easy way to manage these external copies within the application, such as viewing or deleting them once they are no longer needed.

**Describe the solution you'd like**
I would like an option to extract the items from the to-do list into a PDF format directly within the application. This PDF should be easily accessible in a "Saved Documents" section where users can view, download, or delete the PDF list as needed. This functionality will streamline the process of sharing, archiving, and managing to-do lists, making it more efficient and user-friendly.

**Describe alternatives you've considered**
An alternative solution could be to export the to-do list items in other formats such as CSV or plain text. However, these formats might not be as universally accessible and presentable as a PDF. Another alternative could be integrating with third-party document management services, but this would require additional permissions and complicate the user experience.

**Additional context**
The new feature should integrate seamlessly into the existing user interface. For example, the "Saved Documents" section could be added to the main navigation menu, and

**Additional context**
The new feature should integrate seamlessly into the existing user interface. For example, the "Saved Documents" section could be added to the main navigation menu, and each to-do list entry could have an option to "Export as PDF." Users should have intuitive controls for managing these PDFs, including previewing the document within the application, downloading it to their device, or deleting it once the tasks are complete. Here are some visual mockups and screenshots to illustrate the proposed changes:

1. **Main Navigation Menu:**
   - Add a new section labeled "Saved Documents" where users can access all their exported PDFs.

2. **To-Do List Interface:**
   - Each to-do list entry should have an "Export as PDF" option.
   - A confirmation dialog to notify the user once the PDF has been successfully created.

3. **Saved Documents Section:**
   - Display a list of all saved PDFs with options to view, download, or delete each document.
   - Include a preview pane where users can quickly view the contents of the selected PDF without needing to download it.
   
 

https://github.com/dhairyagothi/50_days_50_web_project/assets/136626840/290ca360-515f-4eb5-be2f-870183597e88

By implementing this feature, we aim to enhance the overall usability and functionality of the to-do list application, making it easier for users to manage their tasks and documentation in one place. Atlast, I want to request PA to see the efforts made in enhancement of the current project and assign the lables accordingly your feedback is very important for me.
Thanks

**Comment by dhairyagothi** [comment]
make a PR @atharva012004
