### ISSUE TITLE
wordle project update

### ISSUE THREAD

**Issue by Ayushswirlon** [dhairyagothi/100_days_100_web_project#117]
**Is your feature request related to a problem? Please describe.**
in the wordle game project the word is only one . instead add a csv file of all the words so that new words come after each game is done

**Describe the solution you'd like**
i will add a file of all words so that new word will be fetch every time new game started.

**Describe alternatives you've considered**
alternatively an array of string of words can be given in js so that random words will be choose by the code and will enhance the overall experience of the game.

**Additional context**

**Comment by dhairyagothi** [comment]
Assigned @Ayushswirlon

**Comment by Ayushswirlon** [comment]
should i also add a reset button in frontend and also a loader in the website

**Comment by dhairyagothi** [comment]
@Ayushswirlon add it

**Comment by Ayushswirlon** [comment]
👍

**Comment by Ayushswirlon** [comment]
![Screenshot 2024-06-22 000456](https://github.com/dhairyagothi/50_days_50_web_project/assets/136717301/33808c3e-5322-4ce3-937b-6db34876f500)
![Screenshot 2024-06-22 000518](https://github.com/dhairyagothi/50_days_50_web_project/assets/136717301/dc2cd0b6-491b-4810-b272-3da2f7248861)
![Screenshot 2024-06-22 000634](https://github.com/dhairyagothi/50_days_50_web_project/assets/136717301/9f812122-0e49-431b-9fa8-08c5a1079650)


**updates**
1.had resolve the issue of shuffle words now everyday a new word would be selected
2.made the game in landscape mode for better user experience in laptop and also make it responsive so also can be played with other devices
3.now direct keyboard typing is available 
4. also make the scoreboard more alligned 


**should i make a pr or you want any other changes too**

**Comment by dhairyagothi** [comment]
Assigned @Ayushswirlon

**Comment by dhairyagothi** [comment]
make PR
