### ISSUE TITLE
Adding Tic-Tac-Toe Game Using HTML, CSS, and JavaScript as an newProject

### ISSUE THREAD

**Issue by AnantAgarwaL11** [dhairyagothi/100_days_100_web_project#12]
I propose adding a new project to the repository: a Tic-Tac-Toe game implemented using HTML, CSS, and JavaScript.

**Comment by dhairyagothi** [comment]
Good to go @AnantAgarwaL11 

Please star ⭐ the repo and add files in a seperate folder and also update index. html file so that it can serve directly to main website

Assigned @AnantAgarwaL11 

Go ahead

**Comment by AnantAgarwaL11** [comment]
I have completed my issue but can you please help me with how to commit and
push it back to GitHub .
I'm facing some difficulty in it

**Comment by dhairyagothi** [comment]
Are you using github desktop ?

**Comment by dhairyagothi** [comment]
![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/142989448/4a37c08f-28f6-486f-9c14-1ec7fb4e3420)

Do this two steps then open your forked repo and there you will show contribute option then create a pull request

**Comment by AnantAgarwaL11** [comment]
yes, I am using GitHub desktop thanks for helping

**Comment by dhairyagothi** [comment]
Ya do that and create PR

**Comment by AnantAgarwaL11** [comment]
I have created a PR

**Comment by dhairyagothi** [comment]
Drop your email on discord

**Comment by dhairyagothi** [comment]
#19 merged
