### ISSUE TITLE
adding zomato clone project

### ISSUE THREAD

**Issue by kratik1237** [dhairyagothi/100_days_100_web_project#120]
for your repository of 50 days  50 web project i suggest to add a project of clone of online food delievery site zomato.
plz have a look into this issue and assign this to me .

**Comment by dhairyagothi** [comment]
assigned @kratik1237

**Comment by kratik1237** [comment]
![Screenshot (31)](https://github.com/dhairyagothi/50_days_50_web_project/assets/142149999/bcebc1da-94b0-4b16-8101-4ccd0897f064)
couldn't resolve the conflict of Zomato clone pr please help. @dhairyagothi

**Comment by dhairyagothi** [comment]
ok i will do

**Comment by kratik1237** [comment]
Thank you.@dhairyagothi

**Comment by kratik1237** [comment]
hello @dhairyagothi Mera Zomato clone Nhi ho Rha Hai please do something.

**Comment by dhairyagothi** [comment]
Pr daal rahi h ?

**Comment by dhairyagothi** [comment]
PR daal do i will see don't worry

**Comment by kratik1237** [comment]
Tell me please

**Comment by kratik1237** [comment]
Nhii

**Comment by kratik1237** [comment]
Clone hi nhi ho rha @dhairyagothi

**Comment by kratik1237** [comment]
Itne dino bad ye yha tk hua or ruk gaya @dhairyagothi ![IMG_20240701_201235.jpg](https://github.com/dhairyagothi/50_days_50_web_project/assets/142149999/6a8ce053-873c-4b60-bba1-640c8e5f62b5)

**Comment by kratik1237** [comment]
Clone Ho Gaya 
@dhairyagothi

**Comment by kratik1237** [comment]
Clone Ho gyi but mera Zomato folder.nhj aaya?@dhairyagothi ![IMG_20240701_201451.jpg](https://github.com/dhairyagothi/50_days_50_web_project/assets/142149999/69ea9fe4-963e-42bf-bafe-f5e51b91c8c4)

**Comment by dhairyagothi** [comment]
Pr merge nahi hui isliye nahi aaya wapis dal do

**Comment by kratik1237** [comment]
@dhairyagothi please check pr #208

**Comment by dhairyagothi** [comment]
completed
