### ISSUE TITLE
Creating a Marketing Website Template using HTML, CSS , Js and Bootstrap

### ISSUE THREAD

**Issue by Vansh-kash2023** [dhairyagothi/100_days_100_web_project#121]

**Comment by dhairyagothi** [comment]
make something different from already exits websites

**Comment by kratik1237** [comment]
I am interested in this issue, please assign me.
@dhairyagothi

**Comment by dhairyagothi** [comment]
@Vansh-kash2023  are you working on this issue ??

**Comment by kratik1237** [comment]
Can you assign me this issue ?@dhairyagothi .

**Comment by Vansh-kash2023** [comment]
Not working right now

**Comment by dhairyagothi** [comment]
@kratik1237 assigned

**Comment by kratik1237** [comment]
Sure @dhairyagothi

**Comment by dhairyagothi** [comment]
completed
