### ISSUE TITLE
Adding instruction in the flappy-bird-game (day 30)

### ISSUE THREAD

**Issue by ramsharma3** [dhairyagothi/100_days_100_web_project#122]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Adding instruction as the game start without any instructions and also add previous high score which is initially zero.
By the change first it show instructions like "press space bar to start" and other statistics".

**Comment by dhairyagothi** [comment]
go ahead @ramsharma3 
assigned

**Comment by ramsharma3** [comment]
https://github.com/dhairyagothi/50_days_50_web_project/assets/142149436/1d4e0a67-b13b-48dc-8031-db7e5c1f7f7f

I apologize for the delay. I've been working on resolving the issue. Could you please take a look and let me know your feedback?

**Comment by dhairyagothi** [comment]
make a PR   @ramsharma3
