### ISSUE TITLE
Hover for drop down menu items

### ISSUE THREAD

**Issue by k0msenapati** [dhairyagothi/100_days_100_web_project#125]
**Is your feature request related to a problem? Please describe.**
In the https://50-days-50-web-project.vercel.app/dropdown_navbar/index.html# project, the dropdown UI is not ok. 

**Describe the solution you'd like**
When clicking on any nav item a dropdown appears, it should appear only for hover, and when hover over items they should be highlighted.

**Additional context**
![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/92045934/dae83096-29b6-4280-9d46-858930e4a226)

**Comment by dhairyagothi** [comment]
okay fix it @kom-senapati
