### ISSUE TITLE
Adding Memory Game using Html,Css,Js

### ISSUE THREAD

**Issue by nikitha2611** [dhairyagothi/100_days_100_web_project#13]
Creating a Memory Game using HTML, CSS, and JavaScript involves building a grid of cards that can be flipped to reveal a hidden image or symbol. When two cards with the same image are flipped, they remain visible. Otherwise, they flip back over.

**Comment by dhairyagothi** [comment]
Good to go @nikitha2611 

Please star ⭐ the repo and add files in a seperate folder and also update index. html file so that it can serve directly to main website

Assigned @nikitha2611 

Go ahead

**Comment by nikitha2611** [comment]
![Screenshot 2024-06-17 133239](https://github.com/dhairyagothi/50_days_50_web_project/assets/152257119/fd25ed25-5232-4283-a299-687da776c432)

This is final look how it looks.This shows no.moves and total time to complete the game

**Comment by dhairyagothi** [comment]
@nikitha2611  can you do it in center ??

**Comment by nikitha2611** [comment]
Ok

**Comment by nikitha2611** [comment]
![Screenshot 2024-06-17 141307](https://github.com/dhairyagothi/50_days_50_web_project/assets/152257119/14a82eda-6296-4c27-9ade-b4b8aa3c9d93)
 I made the changes .. Is it ok

**Comment by dhairyagothi** [comment]
@nikitha2611 ya its okay create a pull request i will see it 
with pull request please also drop your email

**Comment by nikitha2611** [comment]
Can u please tell me how can i pull a request

**Comment by dhairyagothi** [comment]
Are you using github desktop @nikitha2611 ??

**Comment by nikitha2611** [comment]
Ya

**Comment by dhairyagothi** [comment]
Open github desktop 
![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/142989448/30a18bf1-48b9-496a-9128-39f2dd73bbde)

**Comment by dhairyagothi** [comment]
do this 2 steps and push your PR first then open repo on website

**Comment by nikitha2611** [comment]
OK thankyouuu

**Comment by dhairyagothi** [comment]
ya ask if anywhere you stuck

**Comment by dhairyagothi** [comment]
#20 completed
