### ISSUE TITLE
Unit Tests for Climate Data Parsing Module

### ISSUE THREAD

**Issue by Yaser-123** [dhairyagothi/100_days_100_web_project#131]
Description:
We need to improve the reliability and robustness of our climate data parsing module by adding comprehensive unit tests. This will ensure that the module correctly parses various climate data formats and handles edge cases gracefully.
Tasks:
1.Set Up Testing Framework
2.Identify Key Functions for Testing
3.Write Unit Tests
4.Run and Verify Tests

https://github.com/dhairyagothi/50_days_50_web_project/assets/140265777/60460137-2480-4504-8887-043033c55fe5

https://github.com/dhairyagothi/50_days_50_web_project/assets/140265777/ae6b079e-b1db-44cf-bf7c-fbd71fcc4c8c

**Comment by dhairyagothi** [comment]
Assigned give title also
