### ISSUE TITLE
Adding Maze game using HTML, CSS and Js

### ISSUE THREAD

**Issue by Yaser-123** [dhairyagothi/100_days_100_web_project#14]

**Comment by dhairyagothi** [comment]
CAN YOU PLEASE PROVIDE SOME DESCRIPTION @Yaser-123

**Comment by Yaser-123** [comment]
The Maze Game is an interactive web application designed to challenge users to navigate through a complex maze using keyboard controls. This game is built with HTML for structure, CSS for styling, and JavaScript for functionality, providing an engaging and visually appealing user experience.

**Comment by dhairyagothi** [comment]
@Yaser-123 Please share some SS if possible there is a similar issue i think

**Comment by Yaser-123** [comment]
https://github.com/dhairyagothi/50_days_50_web_project/assets/140265777/070a2be4-20b8-4974-acc2-0f45225371a5

**Comment by dhairyagothi** [comment]
okay Assigned go for it create a proper PR
Assigned @Yaser-123

**Comment by dhairyagothi** [comment]
Merged #18
