### ISSUE TITLE
Rendering with Flying Lanterns and Koi Fish Models in Three.js

### ISSUE THREAD

**Issue by Yaser-123** [dhairyagothi/100_days_100_web_project#140]
Description:
1.Flying Lanterns
2.Koi Fish
3.Lighting and Shadows

Performance:
Despite the complexity of the models and animations, the project is optimized for performance, ensuring smooth rendering and a seamless user experience. Efficient resource management and careful optimization techniques ensure that the scene runs smoothly even on devices with moderate capabilities

Tech Stack:
1.HTML
2.CSS
3.JS

https://github.com/dhairyagothi/50_days_50_web_project/assets/140265777/715ba466-6f9d-4672-bd63-abc7edbb9724

https://github.com/dhairyagothi/50_days_50_web_project/assets/140265777/d57b3bcd-7e06-4819-a872-773852e9c8f9

**Comment by dhairyagothi** [comment]
@Yaser-123 remove this fish and add this background in index.html looks good

**Comment by Yaser-123** [comment]
Add this project 
I will work on the background today

**Comment by dhairyagothi** [comment]
okay make a PR

**Comment by Yaser-123** [comment]
Bro i changed index.html in climacode can u merge pr
after that i will pr this
i want to got one pr after another

**Comment by dhairyagothi** [comment]
> Bro i changed index.html in climacode can u merge pr after that i will pr this i want to got one pr after another

done
