### ISSUE TITLE
Improving the text to voice converter

### ISSUE THREAD

**Issue by SuhainaFathimaM** [dhairyagothi/100_days_100_web_project#141]
**Improving the text to voice converter**
The UI is not aligned properly and text box is aligned right side and adding more styles to the page will make it more attractive and appealing. 

**To Reproduce**
I would like to add more styles to the ui of the page

**Expected behavior**

**Screenshots**
![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/153417476/4e3d0e6d-e308-45d5-8a79-7a2ed2faf527)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

@dhairyagothi I AM CONTRIBUTING UNDER VSOC 24.  I would like to work on this issue

**Comment by dhairyagothi** [comment]
okay go ahead @SuhainaFathimaM
