### ISSUE TITLE
Expense Manager 

### ISSUE THREAD

**Issue by MonishRaman** [dhairyagothi/100_days_100_web_project#144]
Expense manager is a application which has both front and back end and gives you the exact report of all your expenses with pie chart. by this you can take care of all ur expenses.

tech used is:
React.js

![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/140420819/8b0ca129-1d23-4100-b3fc-83d32d6cccab)

**Comment by dhairyagothi** [comment]
@MonishRaman there is already a budget tracker 
would you like to add only necessary things like this graph in that ?

**Comment by MonishRaman** [comment]
can u please assign this

**Comment by dhairyagothi** [comment]
@MonishRaman already completed by you
