### ISSUE TITLE
Enhanced Budget Tracker: Detailed Categories and Visual Insights

### ISSUE THREAD

**Issue by atharva012004** [dhairyagothi/100_days_100_web_project#146]
Is your feature request related to a problem? Please describe.
Tracking expenses efficiently can be challenging without detailed categorization and visual representation. Users often find it difficult to analyze spending patterns and identify areas for savings or adjustments.

Describe the solution you'd like
I have implemented the following features to enhance expense tracking and analysis:

Detailed Expense Categories: Users can now categorize expenses into predefined categories such as Food, Rent, Entertainment, etc.
Category Management: Users have the flexibility to manage existing categories and create custom categories tailored to their specific needs.
Graphs and Visualizations: Intuitive visual representations include:
Pie Charts and Bar Graphs: Display spending distribution across categories and monthly expenditure trends.
Interactive Charts: Allow users to interact with the charts by clicking on segments to view detailed expense information.
Describe alternatives you've considered
Alternative solutions considered included simpler category structures without user customization, basic tables instead of interactive charts, and static graphs without the ability to drill down into detailed data.

video

https://github.com/dhairyagothi/50_days_50_web_project/assets/136626840/2a589ba4-0cdf-4527-b370-de96ef0c3721

Additional context
This update aims to provide users with a more comprehensive and user-friendly budget tracking experience. Visualizations help users quickly grasp their financial habits, while flexible category management ensures relevance to individual spending patterns.

**Comment by dhairyagothi** [comment]
Add this in previous existing project

**Comment by atharva012004** [comment]
Yes assign me so I will commit changes and raise pr

**Comment by dhairyagothi** [comment]
assigned @atharva012004
