### ISSUE TITLE
Add WORDLE game

### ISSUE THREAD

**Issue by Madhu0-2** [dhairyagothi/100_days_100_web_project#15]
![IMG-20240617-WA0007](https://github.com/dhairyagothi/50_days_50_web_project/assets/126780854/49b109d0-15b6-4703-9b84-3c87d14594f0)

This is clone version of the popular word game 'Wordle' by NYTimes. It uses a different algorithm to choose daily words, which is the motivation to build this. Actually, the word list of original wordle usually gets leaked on twitter and it already shows which word will be there on the day. So overcoming that problem I built this wordle which will choose the word which nobody can know and it will be decided randomly by the code at 12:00:00 AM everyday. It is built using HTML, CSS and Javascript.

**Comment by dhairyagothi** [comment]
Sounds Good Go for it @Madhu0-2 

Please add your project in a particular folder in src and also update index.html so that it can be updated on live server 

Go ahead @Madhu0-2 assigned 
attach SS and video with PR

**Comment by dhairyagothi** [comment]
completed #21
