### ISSUE TITLE
project: add a pastebin service

### ISSUE THREAD

**Issue by externref** [dhairyagothi/100_days_100_web_project#153]
i can add a full-stack pastebin application that users can use to share their code with beautiful themes and syntax highlighting for most programming languages. part of this [original source](https://github.com/externref/glyph)

Stack: SvelteKit, TailwindCSS, Postgresql/SQLite3

**Comment by dhairyagothi** [comment]
Give some ss

**Comment by externref** [comment]
> Give some ss

sure
Home screen:
![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/70657005/3ab22201-24cc-42b3-9969-e07f8aebba22)

Paste page:
![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/70657005/06b34379-68db-4d29-8c87-15f36d9b1c6f)

Output:
https://github.com/dhairyagothi/50_days_50_web_project/assets/70657005/50b526a4-bc7d-48e8-a13d-ff5a09c7c7b0
