### ISSUE TITLE
Upgrading Vanilla JavaScript Calculator to Include Scientific Functions

### ISSUE THREAD

**Issue by atharva012004** [dhairyagothi/100_days_100_web_project#154]
**Is your feature request related to a problem? Please describe.**
The current Vanilla JavaScript Calculator Master is limited to basic mathematical operations. While it serves its purpose adequately, there is a growing need among users for more advanced functionalities. Users, particularly those in technical fields, are increasingly requiring capabilities that go beyond simple arithmetic.

**Describe the solution you'd like**
We propose upgrading the Vanilla JavaScript Calculator Master to include scientific calculator features. This enhancement would enable the calculator to perform complex mathematical operations such as trigonometric functions, logarithmic calculations, exponentials, and more. By integrating these advanced functions, the calculator will become a versatile tool suitable for a wider range of mathematical applications.

**Describe alternatives you've considered**
One alternative would be to develop a separate scientific calculator application. However, integrating these features directly into the existing Vanilla JavaScript Calculator Master would maintain continuity for current users and simplify maintenance efforts. Another consideration is the user interface design to ensure that advanced functions are accessible without compromising the simplicity that users appreciate.

Basic Calculator (original project)
![Screenshot 2024-06-23 135449](https://github.com/dhairyagothi/50_days_50_web_project/assets/136626840/141d7c99-1692-4225-83ef-033c2f083048)

Scientific Calculator (update in the existing project)
![Screenshot 2024-06-23 135503](https://github.com/dhairyagothi/50_days_50_web_project/assets/136626840/645313b7-8330-4b8e-91f2-dba499968c87)

video

https://github.com/dhairyagothi/50_days_50_web_project/assets/136626840/8da7c418-e53f-48f8-b89e-56436326b021

**Additional context**
The update aims to transform the Vanilla JavaScript Calculator Master into a comprehensive tool for both basic and advanced mathematical computations. This enhancement aligns with user feedback and industry trends towards more robust calculator functionalities. We believe that implementing these changes will enhance user satisfaction and broaden the utility of the application. Please review these efforts to incorporate advanced mathematical operations into the core of the project. Your consideration of bonus points for this effort would be greatly appreciated.

**Comment by dhairyagothi** [comment]
go ahead @atharva012004
