### ISSUE TITLE
Add 3D Background Using HTML, CSS, and Three.js

### ISSUE THREAD

**Issue by Yaser-123** [dhairyagothi/100_days_100_web_project#156]
Request:

We would like to enhance the visual appeal of our website by incorporating a dynamic 3D background using HTML, CSS, and Three.js. This background will add an engaging and modern touch to our site's user experience.

Requirements:
1.Setup Three.js Environment
2.Create 3D Background Scene
3.Integrate with HTML and CSS
4.Performance Optimization
5.Cross-browser Compatibility

https://github.com/dhairyagothi/50_days_50_web_project/assets/140265777/6b95a295-2c74-4732-8cd6-54faf0c11f97

**Comment by Yaser-123** [comment]
https://github.com/dhairyagothi/50_days_50_web_project/assets/140265777/24fe9fde-2749-41d2-a798-87f90718e6e8

**Comment by dhairyagothi** [comment]
Do background more dark 
And do some blur @Yaser-123

**Comment by Yaser-123** [comment]
https://github.com/dhairyagothi/50_days_50_web_project/assets/140265777/ce909465-4675-4ad5-bd7a-29dd1cb8ef9b

**Comment by kratik1237** [comment]
I am interested in this issue, please assign me.
@dhairyagothi

**Comment by Yaser-123** [comment]
https://github.com/dhairyagothi/50_days_50_web_project/assets/140265777/00480080-6def-4a02-a5c9-a94c6e6b6e9a

Bro specify what color u need for the latern,the burning light and the background so i can make the background according to u

**Comment by dhairyagothi** [comment]
@Yaser-123 add scroll bar colour and do some more blur

**Comment by Yaser-123** [comment]
https://github.com/dhairyagothi/50_days_50_web_project/assets/140265777/f316180d-e1df-40b4-9ebc-36e8e80bb1ff

Is it ok.

**Comment by dhairyagothi** [comment]
I am changing complete UI merging a new PR still i will assign you hard label make a PR @Yaser-123
