### ISSUE TITLE
want to add a new project RAZORPAY CLONE

### ISSUE THREAD

**Issue by bhagwan8815** [dhairyagothi/100_days_100_web_project#162]
Hey i am Bhagwan Singh rana .
i want to add new project in your  repository 50 _day_50_wev_projects.

the project is Razorpay clone. Razoray is the only payments solution in India that allows businesses to accept. process and disburse payments modes including credit card. debit card . Netbanking.  etc.
![WhatsApp Image 2024-06-24 at 11 57 00_1fa7c458](https://github.com/dhairyagothi/50_days_50_web_project/assets/130534171/4b26be0a-5b32-47be-8835-b48d50103667)
![WhatsApp Image 2024-06-24 at 11 57 22_b1602304](https://github.com/dhairyagothi/50_days_50_web_project/assets/130534171/ad2ae272-0899-4271-a9e2-c97ee239c3fe)
![WhatsApp Image 2024-06-24 at 11 57 37_518d6fbc](https://github.com/dhairyagothi/50_days_50_web_project/assets/130534171/ab9d1d0a-856c-4fe8-bfb8-933fc8e241b6)

**Comment by dhairyagothi** [comment]
assiged @bhagwan8815

**Comment by dhairyagothi** [comment]
completed
