### ISSUE TITLE
corrected The palidrome generator

### ISSUE THREAD

**Issue by Krishna100604** [dhairyagothi/100_days_100_web_project#163]
palindrome generator is not working properly so  made changes like if you enter the string which is palindrome like if you enter NITIN it will return NITIN and if you give the string which is not palindrome it will return name+(reverse of name) which is automatically become palindrome   

https://github.com/dhairyagothi/50_days_50_web_project/assets/110299021/40e1560c-7965-42fd-828c-b25bbbaf86b9

**Comment by Krishna100604** [comment]
@dhairyagothi  assign me under vsoc'24

**Comment by dhairyagothi** [comment]
Assigned @Krishna100604

**Comment by Krishna100604** [comment]
@dhairyagothi merge last PR i create for ping game

**Comment by dhairyagothi** [comment]
COMPLETED #160
