### ISSUE TITLE
Adding Glowing Social media Icons

### ISSUE THREAD

**Issue by Yaser-123** [dhairyagothi/100_days_100_web_project#168]
Adding social media glowing icons
1.Responsive
2.Appealing
3.Beautiful

https://github.com/dhairyagothi/50_days_50_web_project/assets/140265777/5b8a435a-3049-48e2-9511-1ecbbb842cb6

**Comment by dhairyagothi** [comment]
ok add @Yaser-123

**Comment by dhairyagothi** [comment]
completed
