### ISSUE TITLE
Creating a new project - blog website using html css javascript 

### ISSUE THREAD

**Issue by Ayushswirlon** [dhairyagothi/100_days_100_web_project#169]
Hey there, I would like to contribute in your repo 50 days 50 web project by adding a web project of blog website. This will be a functional websites with great features. Plz assign the issue so that I can start working on it.

**Comment by dhairyagothi** [comment]
done @Ayushswirlon 
do changes and ss while making PR

**Comment by Ayushswirlon** [comment]
hey @dhairyagothi i was going to start the work on blog page but someone already do it #184 and mine was #169
so should i make a new one or just update the already one as it was too basic

**Comment by dhairyagothi** [comment]
He has made something else 
you continue with your issue no worries i will merge and give points 
make a PR after completing @Ayushswirlon

**Comment by Ayushswirlon** [comment]
ok then thanks 👍

**Comment by dhairyagothi** [comment]
completed
