### ISSUE TITLE
i have find a bug in your Discord projects.

### ISSUE THREAD

**Issue by bhagwan8815** [dhairyagothi/100_days_100_web_project#176]
**Describe the bug**
hey i am Bhagwan Singh Rana , i have find a bug in your Discord Project.  the bug is : There is no file ( index.html , style.css etc)available in your Discord Project.

**To Reproduce**

**Expected behavior**
i want solve this bug by completing this projects , please assign me,

**Screenshots**
![img-discord-1](https://github.com/dhairyagothi/50_days_50_web_project/assets/130534171/a2fc2868-344a-4e71-895e-e298631c94bb)
![img-discord-2](https://github.com/dhairyagothi/50_days_50_web_project/assets/130534171/5a51b9d9-ee1d-433d-9aa5-411fb66a4c4e)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dhairyagothi** [comment]
assigned @bhagwan8815
