### ISSUE TITLE
 Hologram Button for Enhanced User Interaction

### ISSUE THREAD

**Issue by Yaser-123** [dhairyagothi/100_days_100_web_project#179]
Develop and implement a hologram button to enhance user interaction on the website. This button should feature a 3D holographic effect that responds to user hover and click actions, providing a futuristic and engaging experience. The button should be compatible with all modern browsers and responsive across various devices. Additionally, ensure the button integrates seamlessly with the existing website design and functionality. Test thoroughly to guarantee smooth performance and visual appeal.

https://github.com/dhairyagothi/50_days_50_web_project/assets/140265777/103faf03-9d53-4c36-81bc-389fe918d3b9

**Comment by dhairyagothi** [comment]
assigned @Yaser-123
