### ISSUE TITLE
the user interface is quite basic in Digital_Clock and there is no background and good stylings.

### ISSUE THREAD

**Issue by Shivakumarjagadam** [dhairyagothi/100_days_100_web_project#180]
Problem Description:
Currently, our digital clock project displays the current time, day of the week, and date with three style options (Classic, Modern, Futuristic) and an alarm setting feature. However, the user interface is quite basic and could benefit from enhanced design elements.

Identified Issues:

1.Lack of Visual Appeal :  The design is minimalistic, and there are no vibrant colors or attractive background elements.
2.User Interaction : The buttons and other interactive elements are plain and not user-friendly.

Proposed Solutions :

Enhancing Buttons: Introduce colorful and styled buttons for better user interaction. Each button (Classic, Modern, Futuristic, Local Time, Set Alarm) can be uniquely styled to make the interface more intuitive and visually appealing.
Background Layout Design: Add a background image or gradient to enhance the overall look and feel of the clock. This will make the digital clock more engaging and pleasant to use.

Implementation Plan:

1. Buttons: Use CSS to style buttons with different colors, hover effects, and improved typography.
2. Background: Add a background image or gradient using CSS.

how it is looking(original):

![Screenshot 2024-06-26 222314](https://github.com/dhairyagothi/50_days_50_web_project/assets/154302898/e537ddc5-50be-4c6f-b723-31d01148cb00)

**Comment by dhairyagothi** [comment]
![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/142989448/8e67d033-6e79-4f25-89c9-3e8d1dde9e20)


@Shivakumarjagadam it looks like this

**Comment by Shivakumarjagadam** [comment]
@dhairyagothi  sorry  , i didn't  notice that.

**Comment by dhairyagothi** [comment]
okay np closing issue

**Comment by Shivakumarjagadam** [comment]
@dhairyagothi  but im unable to see ,that updated version of digital clock???

**Comment by dhairyagothi** [comment]
> @dhairyagothi but im unable to see ,that updated version of digital clock???

https://50-days-50-web-project.vercel.app/digital_clock/digitalclock.html
