### ISSUE TITLE
Blog Page

### ISSUE THREAD

**Issue by k0msenapati** [dhairyagothi/100_days_100_web_project#184]
The blog page will have 2 parts a blog component (image, title, text) to show the blog and another sidebar to like, share, bookmark and comment on the blog.

Rough idea - 
![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/92045934/ede78977-8e36-4155-ab5e-6d66309f0f55)

**Comment by dhairyagothi** [comment]
assigned @kom-senapati
