### ISSUE TITLE
Adding a new frontend project - Dental Service Website

### ISSUE THREAD

**Issue by atharva012004** [dhairyagothi/100_days_100_web_project#185]
About Website-
Smile Care is a comprehensive dental service website designed to provide users with an intuitive platform for booking appointments, finding the best doctors, and enhancing their overall dental care experience. The frontend of the website is developed using HTML, CSS, JavaScript, and utilizes the Bootstrap framework extensively for a polished UI/UX.

Features -
Appointment Booking: Allows users to schedule appointments with preferred dates and times.
Doctor Search: Enables users to find and learn about the best doctors available for their specific dental needs.
and many more... 

The Smile Care frontend project enhances user experience through intuitive design, robust functionality, and seamless integration of modern web technologies. By leveraging HTML, CSS, JavaScript, and Bootstrap, we have ensured a scalable and maintainable solution for Smile Care's dental service platform.

video

https://github.com/dhairyagothi/50_days_50_web_project/assets/136626840/15c77d30-3c89-448a-ae44-3dcb939adfe3

**Comment by dhairyagothi** [comment]
assigned @atharva012004
