### ISSUE TITLE
Want to Change the UI of  Email Validator projects and make it responsive.

### ISSUE THREAD

**Issue by bhagwan8815** [dhairyagothi/100_days_100_web_project#188]
**Describe the bug**
the Email validator project in your repository is not responsive and have not good UI.

**To Reproduce**

**Expected behavior**
I want to change the UI of Email Validator projects and make it more responsive.

**Screenshots**
![email-validator-img](https://github.com/dhairyagothi/50_days_50_web_project/assets/130534171/27995ebd-ba27-4408-8050-94709e5fd9b2)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dhairyagothi** [comment]
assigned @bhagwan8815
