### ISSUE TITLE
Request for  Feature Addition to send user prompt and UI Design Enhancement , in Ai chatbot project

### ISSUE THREAD

**Issue by BrajRaj89** [dhairyagothi/100_days_100_web_project#192]
I am always frustrated when I have to click the send button to submit my message in the chatbot. It would be more efficient if I could press the enter key to submit my message instead.

Solution
I would like the chatbot to support submitting messages by pressing the enter key in addition to the send button. This should allow users to submit their prompts quickly and easily.

I have attached screenshots and a video demonstrating the desired functionality. The video shows how pressing enter should send the prompt to the API. Additionally, I would like to redesign the UI of the chatbot. Some design changes I have made are included in the attachments.

 before changing 
https://github.com/dhairyagothi/50_days_50_web_project/assets/147842418/5f9e73f6-aeda-40d1-a1b7-37847e64846d

video of the changes,
https://github.com/dhairyagothi/50_days_50_web_project/assets/147842418/c202385b-3014-4c93-a701-876ea637a2a5

**Comment by dhairyagothi** [comment]
@BrajRaj89 
give that blue background ``` height :90vh ```
use some dark blue colour and white text 
and give a title ```AI Chatbot ```

**Comment by BrajRaj89** [comment]
okay , I am working on it
