### ISSUE TITLE
 Planet Research Website

### ISSUE THREAD

**Issue by Yaser-123** [dhairyagothi/100_days_100_web_project#195]
1.Educational Resource
2.Research and Data Sharing
3.Archive and Repository

Challenges of Building a Planet Research Website

1.Complex Data Integration
2.User Experience and Accessibility
3.Scalability and Performance
4.Content Management
5.Technical Expertise

Tech Stack:
1.HTML
2.CSS
3.JS
4.HML

https://github.com/dhairyagothi/50_days_50_web_project/assets/140265777/97b330f3-fb80-427c-979e-f39acc15f5bd

**Comment by dhairyagothi** [comment]
@Yaser-123 please mention source also from where u have made thhis
