### ISSUE TITLE
Enhancing the plantwebsite by making it responsive and adding more features 

### ISSUE THREAD

**Issue by Ayushswirlon** [dhairyagothi/100_days_100_web_project#196]
**Is your feature request related to a problem? Please describe.**
The plant website is basic and not responsive for smaller device.

**Describe the solution you'd like**
 The goal is to make website responsive and adding transition and hover effect to make it more cooler

**Describe alternatives you've considered**

**Additional context**

**Comment by dhairyagothi** [comment]
which website specify its name correctly @Ayushswirlon

**Comment by Ayushswirlon** [comment]
Day 19 plant website

**Comment by dhairyagothi** [comment]
ok work on it
