### ISSUE TITLE
want to add Dev-Detective-Github project

### ISSUE THREAD

**Issue by bhagwan8815** [dhairyagothi/100_days_100_web_project#198]
hey i am BhagwanSingh Rana , i want to add  a new project in your repository 50_days_50_web_projects which is a Dev-Detective-Github Project, the projects is find the user profile by user name .
i am also add extra features in this projects which is light and dark screen mode .

https://github.com/dhairyagothi/50_days_50_web_project/assets/130534171/6d2b3537-e525-45ee-b755-6fa0d2b13920

**Comment by dhairyagothi** [comment]
Already there @bhagwan8815 
which web technologies you have used ?
update the previous one ui is good

**Comment by bhagwan8815** [comment]
I used Html css and javascript and APIs.

**Comment by dhairyagothi** [comment]
okay @bhagwan8815 update previous one github profile finder and make a PR 
remove previous one and do accordingly
