### ISSUE TITLE
please add me to ur project

### ISSUE THREAD

**Issue by MonishRaman** [dhairyagothi/100_days_100_web_project#2]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dhairyagothi** [comment]
@MonishRaman please describe the issue on which you want to work 

Once you have added a issue i will assign that issue to you than you start working on it and make a PR accordingly 

There is nothing like that to add in repo 

Have you understand ??

**Comment by MonishRaman** [comment]
sorry sir, iam a fresher and this is my first time contribution on github.

**Comment by dhairyagothi** [comment]
> sorry sir, iam a fresher and this is my first time contribution on github. 
> 

No problem 
Good luck assigned issue
