### ISSUE TITLE
Inhacement in Blog page day 59

### ISSUE THREAD

**Issue by ramsharma3** [dhairyagothi/100_days_100_web_project#201]
**Is your feature request related to a problem? Please describe.**
The icon of like share are big can change their size also the overall website is not like sorted want to sort it.

**Describe the solution you'd like**

**Describe alternatives you've considered**
changes by adding heading resize icons and image.

**Additional context**

**Comment by ramsharma3** [comment]
hey can you check the enhancement attached with this message

 

https://github.com/dhairyagothi/50_days_50_web_project/assets/142149436/d1a478de-b38b-4728-8e0e-2c8d61cb46da

https://github.com/dhairyagothi/50_days_50_web_project/assets/142149436/7d65ae4c-25ae-461e-aa0b-97668be4d9af

https://github.com/dhairyagothi/50_days_50_web_project/assets/142149436/d50b7cd5-1614-48df-8642-1dbb708780b5

And can you please change it to hard as it took a lot of effort and time.

**Comment by ramsharma3** [comment]
can I make PR

**Comment by dhairyagothi** [comment]
make PR then i will check and suggest changes

**Comment by k0msenapati** [comment]
No this is not the idea
Its just a blog page not a website where you put about, contact, login
If we create a blog application there we can use this page as a blog page don't change it like this

**Comment by ramsharma3** [comment]
PR generated, check it
