### ISSUE TITLE
styling the buttons in TODOLIST .

### ISSUE THREAD

**Issue by Shivakumarjagadam** [dhairyagothi/100_days_100_web_project#202]
when entering into saved documents, the view ,download buttons are looking very small and basic stylings..

**Describe the solution you'd like**

Color: The buttons will have background with white text for better visibility.
Size and Padding: We will increase the padding to  make the buttons larger and easier to click.
Hover Effects: The buttons will change to a slightly dark in colour when hovered over to provide visual feedback.

**Additional context**
how it is looking,Actual pic(Original):

![Screenshot 2024-06-28 221004](https://github.com/dhairyagothi/50_days_50_web_project/assets/154302898/0a8fb043-63b9-4b59-814a-fa34d1c35f9d)

**Comment by dhairyagothi** [comment]
go ahead @Shivakumarjagadam

**Comment by Shivakumarjagadam** [comment]
check this PR #216
