### ISSUE TITLE
not responsive Discord project.

### ISSUE THREAD

**Issue by bhagwan8815** [dhairyagothi/100_days_100_web_project#203]
**Describe the bug**
hey i am BhagwanSingh Rana , i have to find a bug in your Discord project , which is the project is not Responsive in nature and have a not good UI for small and medium screen. 

**To Reproduce**

**Expected behavior**
i want to make it responsive, by which it have a good UI for small and medium screens. 

**Screenshots**

https://github.com/dhairyagothi/50_days_50_web_project/assets/130534171/cf10b540-1897-448c-bae9-0cf13edd7fc4

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dhairyagothi** [comment]
Tell me day and date of projrct @bhagwan8815
