### ISSUE TITLE
want to add Currency_Converter Project.

### ISSUE THREAD

**Issue by bhagwan8815** [dhairyagothi/100_days_100_web_project#206]
hey i am Bhagwan Singh Rana .
i  want to add a new project in your Repository which is a Currency_Converter Project.
i make this project using html css and javascript , i also use API in this project.
please assign me.

https://github.com/dhairyagothi/50_days_50_web_project/assets/130534171/5b796b25-2dfb-4d36-85d9-ed8322332d63

**Comment by bhagwan8815** [comment]
Pls check this issue bhai

**Comment by dhairyagothi** [comment]
go ahead
