### ISSUE TITLE
added consultation history with date time and status and changed design of page 

### ISSUE THREAD

**Issue by Krishna100604** [dhairyagothi/100_days_100_web_project#213]
![Screenshot (180)](https://github.com/dhairyagothi/50_days_50_web_project/assets/110299021/f282e590-7bb1-4d6c-876c-dff10c7909af)
![Screenshot (179)](https://github.com/dhairyagothi/50_days_50_web_project/assets/110299021/13bbbd76-11e0-4465-8a76-173b37cb1db4)

@dhairyagothi  kindly assign me this

**Comment by dhairyagothi** [comment]
assigned @Krishna100604
