### ISSUE TITLE
Enhanced Typewriter Project with Improved User Interactivity and Customization

### ISSUE THREAD

**Issue by atharva012004** [dhairyagothi/100_days_100_web_project#215]
Is your feature request related to a problem? Please describe.
The current typewriter project provides a very basic user experience, which is not engaging for users. The lack of interactivity and advanced features makes it less useful and enjoyable.

Describe the solution you'd like
I have implemented several enhancements to improve the user experience:

1.User Input: Users can now enter their own text to see how it appears on the typewriter.
2.Resume and Pause Buttons: Added buttons to allow users to pause and resume the typewriter effect, providing more control over the typing process.
3.Speed Bar: Introduced a speed bar, enabling users to adjust the typing speed to their preference.
4.Background Toggle: Added a background toggle button, allowing users to switch between dark and light UI modes as desired.
Describe alternatives you've considered
An alternative solution considered was keeping the typewriter effect static without user interaction. However, this did not address the need for a more dynamic and customizable user experience. Another option was to add only the resume and pause functionality, but this alone would not provide enough improvement in interactivity and user engagement.

Additional context
The updated features make the typewriter project more versatile and user-friendly. Below are some screenshots of the new interface with the added functionalities.

Before 
![Screenshot 2024-07-03 192525](https://github.com/dhairyagothi/50_days_50_web_project/assets/136626840/bfb7242f-c11e-4ad1-a9f5-578020fe85af)

After 

https://github.com/dhairyagothi/50_days_50_web_project/assets/136626840/f938d96d-072c-4d51-bd18-05d2187e1916

**Comment by atharva012004** [comment]
I've Completely transformed the typewritter project you can see the demo video and screenshot of previous basic typewritter

**Comment by dhairyagothi** [comment]
assigned @atharva012004
