### ISSUE TITLE
want to add Spotify_Project

### ISSUE THREAD

**Issue by bhagwan8815** [dhairyagothi/100_days_100_web_project#219]
hey i am BhagwanSingh Rana, i want to add a new project in your Repository which is Spotify Clone Projects.
please assign me it.

https://github.com/dhairyagothi/50_days_50_web_project/assets/130534171/97610865-bf6d-4b53-9e07-04c1092c6aac

**Comment by dhairyagothi** [comment]
assigned @bhagwan8815
