### ISSUE TITLE
Add Speech-to-Text Feature to Text-to-Voice Converter Project

### ISSUE THREAD

**Issue by BrajRaj89** [dhairyagothi/100_days_100_web_project#220]
Providing a speech-to-text feature will enhance the user experience by allowing them to input text through voice commands. 

**Describe the solution you'd like**
I would like to propose an enhancement to our existing text-to-speech converter project by adding a speech-to-text functionality. This feature will allow users to speak into their devices, and the spoken words will be converted into text, which can then be used for various purposes within the application.

**Describe alternatives you've considered**
 Utilize a reliable speech recognition API (such as Google Speech-to-Text, Microsoft Azure Speech Service, or IBM Watson) to capture and convert speech into text.
User Interface Enhancement: Add a microphone icon or a dedicated button in the user interface that users can click to start and stop the speech-to-text process.

**Comment by dhairyagothi** [comment]
already there as day 48 #132

**Comment by BrajRaj89** [comment]
#132 is about text to speech convertor and i want to add the feature that user can speak and this will be converted into text
in the project text to speech convertor

**Comment by dhairyagothi** [comment]
okay assigned @BrajRaj89
