### ISSUE TITLE
styling the home page  using hovers,cursor .

### ISSUE THREAD

**Issue by Shivakumarjagadam** [dhairyagothi/100_days_100_web_project#222]
To add hover effects and custom cursors to the navigation links in an auto-background image slider.

Problem Description:
I want to enhance the user interface of an auto-background image slider by adding hover effects to the navigation links ("HOME," "CONTACT US," and "ABOUT US"). Specifically, I want to:

1. Change the cursor to a pointer when hovering over the navigation links.
2.. Change the background color of the links when hovered over.

**Describe the solution you'd like**

Solutions:
1.Changing the Cursor on Hover:

2.Use the cursor property in CSS to change the cursor to a pointer when the user hovers over the navigation links.
Changing the Background Color on Hover:

**Additional context**
how its looks:
![Screenshot 2024-07-05 155004](https://github.com/dhairyagothi/50_days_50_web_project/assets/154302898/e535926d-206e-43cb-a15d-72e28eb0db9d)

**Comment by dhairyagothi** [comment]
Assigned @Shivakumarjagadam

**Comment by Shivakumarjagadam** [comment]
please check my PR  #231
