### ISSUE TITLE
want to change the UI of Password_Generator Project.

### ISSUE THREAD

**Issue by bhagwan8815** [dhairyagothi/100_days_100_web_project#223]
**Describe the bug**
hey i am BhagwanSingh Rana , i want to change the UI of Password_Generator Projects. and make it more Attractive UI.

**To Reproduce**

**Expected behavior**
in this project the UI is not  a good , i want to change it.

**Screenshots**

https://github.com/dhairyagothi/50_days_50_web_project/assets/130534171/013f6de6-cee7-4879-ba77-e594a49b6d3f

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dhairyagothi** [comment]
Assigned @bhagwan8815
