### ISSUE TITLE
Enhancement: Add 3D Responsive Rotating Card

### ISSUE THREAD

**Issue by Yaser-123** [dhairyagothi/100_days_100_web_project#224]
I have developed a 3D responsive rotating card feature for the HelpingHands 2.0 website. This enhancement aims to improve the visual appeal and user engagement. Below are the details:

Title: 3D Responsive Rotating Card
Description: A visually striking card component that rotates in 3D when interacted with. This card is fully responsive, ensuring optimal display on all devices.
Features:
Smooth 3D rotation effect
Responsive design for various screen sizes
Easy integration with existing content

https://github.com/dhairyagothi/50_days_50_web_project/assets/140265777/61f930b1-97aa-43da-aa91-26e6ae635694

**Comment by dhairyagothi** [comment]
Assigned @Yaser-123
