### ISSUE TITLE
changes in indian flag 

### ISSUE THREAD

**Issue by shreya-2410** [dhairyagothi/100_days_100_web_project#225]
**Is your feature request related to a problem? Please describe.**
it is not responsive .the design and layout can be better 

**Describe the solution you'd like**
we can make it responsive and also interactive by adding some hover effects and animations

**Describe alternatives you've considered**
By implementing these changes,  Indian flag page should be more visually appealing, interactive, accessible, and performant.

**Additional context**
pls assign this to me under vsoc

**Comment by dhairyagothi** [comment]
Assigned @shreya-2410
