### ISSUE TITLE
Social Media Glowing icons improvemnt

### ISSUE THREAD

**Issue by shreya-2410** [dhairyagothi/100_days_100_web_project#226]
**Is your feature request related to a problem? Please describe.**
add hover effects and make it responsive

**Describe the solution you'd like**
Update general styling for body, header, footer, and icons.

**Describe alternatives you've considered**
Added interactive hover effects for icons.

**Additional context**
would try to improve its overall style pls assign under vsoc'24

**Comment by dhairyagothi** [comment]
Share SS while making PR 
Assigned @shreya-2410
