### ISSUE TITLE
Country Capital Quiz project

### ISSUE THREAD

**Issue by Prashant-2024** [dhairyagothi/100_days_100_web_project#23]
**Is your feature request related to a problem? Please describe.**
A game of guessing and knowledge, similar to GeoGuesser. user will pick a capital city and for the provided country, if correct score increase and if not user will have to restart.

**Describe the solution you'd like**
We can use HTML, CSS, JS, Node.js, Express.js, to implment this mini project

**Comment by dhairyagothi** [comment]
Sounds good go for it @Prashant-2024 

Assigned @Prashant-2024 
please also update index.html and attach SS
