### ISSUE TITLE
Interactive 3D Social Media Icon

### ISSUE THREAD

**Issue by Yaser-123** [dhairyagothi/100_days_100_web_project#230]
This project features an innovative 3D social media icon created using HTML and CSS. The icon offers a visually engaging, interactive experience, leveraging modern web design techniques to add depth and dynamism. By utilizing CSS transformations and animations, the icon not only captures attention but also enhances user interaction, making it a perfect addition to any contemporary website or application. The project demonstrates the power of combining HTML structure with advanced CSS styling to create compelling and functional web elements

https://github.com/dhairyagothi/50_days_50_web_project/assets/140265777/a495ed7f-68de-45c2-b7d0-42c84c5c29d4

**Comment by dhairyagothi** [comment]
you have already added a similar thing @Yaser-123

**Comment by Yaser-123** [comment]
Yeah but it doesen't had hover effect and animation
and its dynamic.

**Comment by Yaser-123** [comment]
You can think of it as it's upgraded version.

**Comment by dhairyagothi** [comment]
so upgrade previous one @Yaser-123

**Comment by Yaser-123** [comment]
They are different

https://github.com/dhairyagothi/50_days_50_web_project/assets/140265777/71f99b17-689d-4e39-80cc-ac0dd0a25d70

**Comment by Yaser-123** [comment]
They are two different type of icon's

**Comment by dhairyagothi** [comment]
add different type in similar html file
