### ISSUE TITLE
Adding a Navbar in website

### ISSUE THREAD

**Issue by dhairyagothi** [dhairyagothi/100_days_100_web_project#236]
**Is your feature request related to a problem? Please describe.**
Adding a navbar that will contain logo and github logo with matching theme of website and blurry position sticky

Comment to get assigned

**Comment by atharva012004** [comment]
I have designed a navbar as per your requirements. It features a sleek and classy look, providing an better visual experience. The text '50 Days, 50 Web Projects' has been replaced with a logo image, which is customized with hover and other effects using CSS to enhance its interactivity. Please find the attached video showcasing the design and its functionality.

https://github.com/dhairyagothi/50_days_50_web_project/assets/136626840/8c31f4fd-9866-412d-925b-e0c3ca5a37a0

**Comment by atharva012004** [comment]
I have designed a navbar as per your requirements. It features a sleek and classy look, providing a better visual experience. The text '50 Days 50 Web Projects' has been replaced with a logo image, which is customized with hover and other effects using CSS to enhance its interactivity. Please find the attached video showcasing the design and its functionality.


https://github.com/dhairyagothi/50_days_50_web_project/assets/136626840/3531dc6f-2d22-43e5-bd11-bd8886b5fb01

**Comment by 1754riya** [comment]
@dhairyagothi, Please assign me this issue.

**Comment by dhairyagothi** [comment]
@atharva012004 make a seperate issue and PR please

**Comment by atharva012004** [comment]
> @atharva012004 make a seperate issue and PR please

Issue is raised and pr is also created pls assign that & you can merge it to main
