### ISSUE TITLE
Adding a footer in website

### ISSUE THREAD

**Issue by dhairyagothi** [dhairyagothi/100_days_100_web_project#237]
**Is your feature request related to a problem? Please describe.**

adding a footer in website that will contain links to diiferent pages and made by dhairya and contributors with social icons 

comment to get assigned

**Comment by DavidMarcosJ** [comment]
I would like to participate in the creation of the website footer.

**Comment by dhairyagothi** [comment]
Create a seperate issue @DavidMarcosJ

**Comment by DavidMarcosJ** [comment]
I've already done it

**Comment by 1754riya** [comment]
Please assign me this issue.

**Comment by dhairyagothi** [comment]
> I've already done it

will check your issue
