### ISSUE TITLE
New Footer

### ISSUE THREAD

**Issue by DavidMarcosJ** [dhairyagothi/100_days_100_web_project#240]
Add new footer with social media and contributors

Example:
![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/163770734/1c36fe02-3ff3-41d5-9913-51d00f06c849)

**Comment by dhairyagothi** [comment]
make a PR @DavidMarcosJ small the icons of contributors

**Comment by DavidMarcosJ** [comment]
@dhairyagothi Done

**Comment by dhairyagothi** [comment]
@DavidMarcosJ contact me on discord

**Comment by DavidMarcosJ** [comment]
@dhairyagothi Okey,I have already sent you a friend request
