### ISSUE TITLE
Adding New Navbar to index.html

### ISSUE THREAD

**Issue by atharva012004** [dhairyagothi/100_days_100_web_project#242]
I have designed a navbar as per your requirements. It features a sleek and classy look, providing a better visual experience. The text '50 Days, 50 Web Projects' has been replaced with a logo image, which is customized with hover and other effects using CSS to enhance its interactivity. Please find the attached video showcasing the design and its functionality.

https://github.com/dhairyagothi/50_days_50_web_project/assets/136626840/874e613a-6684-40fe-93c8-451f89b88345

**Comment by dhairyagothi** [comment]
assigned @atharva012004

**Comment by atharva012004** [comment]
PR is created you can go ahead to merge it to main branch
