### ISSUE TITLE
Want to Add Word Dictionary project

### ISSUE THREAD

**Issue by BrajRaj89** [dhairyagothi/100_days_100_web_project#245]
I would like to propose the addition of a word dictionary project to our project repository.
This project will allow users to search for word definitions, get suggestions for similar words.

Here, I am providing a video that demonstrates the project word dictionary.

https://github.com/dhairyagothi/50_days_50_web_project/assets/147842418/c55b1ee7-b0bc-4183-9991-d0007a7ea4cb

**Comment by dhairyagothi** [comment]
assigned @BrajRaj89
