### ISSUE TITLE
find a bug in Weather-Forcasting Project

### ISSUE THREAD

**Issue by bhagwan8815** [dhairyagothi/100_days_100_web_project#253]
**Describe the bug**
in Weather-Forcasting projects when we search  weather for a city, then there is no result show he show undefined. 

**To Reproduce**

**Expected behavior**
i want to solve this bug and also update UI of weather-forcasting projects, and add grant access location features, this features is basically take permission to user to access there live location.

**Screenshots**

https://github.com/dhairyagothi/50_days_50_web_project/assets/130534171/45dd137c-fcf5-41c0-8961-5fcc26f12b2a

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dhairyagothi** [comment]
already exists find something new'
