### ISSUE TITLE
Hangman Game

### ISSUE THREAD

**Issue by Madhu0-2** [dhairyagothi/100_days_100_web_project#26]
**Hangman** is a word-guessing game where players try to guess all the letters of a randomly generated word within a given number of tries. There is also a hangman illustration that will progressively appear on the gallows for each incorrect guess. Built using HTML, CSS, and JavaScript

**Comment by dhairyagothi** [comment]
Good to see u again @Madhu0-2 
go ahead assigned

**Comment by dhairyagothi** [comment]
@Madhu0-2  updates

**Comment by dhairyagothi** [comment]
not done
