### ISSUE TITLE
Bug : Copyright year 

### ISSUE THREAD

**Issue by Meetjain1** [dhairyagothi/100_days_100_web_project#262]
**Describe the bug**
Currently copyright year is displaying using direct copy paste of text. 

**To Reproduce**

**Expected behavior**
It should be dynamic in nature that is it should fetch the current year using javascript.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

@dhairyagothi assign this issue to me I will fix this bug . Thanks 
I am working under VSOC

**Comment by dhairyagothi** [comment]
assigned @Meetjain1
