### ISSUE TITLE
Feat : creating a logo + Adding a favicon 

### ISSUE THREAD

**Issue by Meetjain1** [dhairyagothi/100_days_100_web_project#263]
**Is your feature request related to a problem? Please describe.**
Currenty our website have no logo and hence no favicon 

**Describe the solution you'd like**
Want to create a logo and hence will add that logo as a favicon also 

**Describe alternatives you've considered**

**Additional context**

@dhairyagothi assign this issue to me , I am working under VSOC. Thanks

**Comment by dhairyagothi** [comment]
make a new one on your own @Meetjain1

**Comment by Meetjain1** [comment]
Hi @dhairyagothi I have designed some logos let me know which logo suits more for this website .

![5D3](https://github.com/user-attachments/assets/a5689391-507d-4986-a3cb-e9ba94e7f639)
![5D2](https://github.com/user-attachments/assets/76faaa44-49f4-40fb-bbb1-b748bf352587)
![5D1](https://github.com/user-attachments/assets/5c57f38e-2e32-491d-8f6b-9fd5bb9e092e)
![5D5](https://github.com/user-attachments/assets/be79c739-8200-4d96-af99-52a74c4c5724)
![5D4](https://github.com/user-attachments/assets/2c6d4e37-8e60-40c8-b104-85e3d7167a3b)

**Comment by dhairyagothi** [comment]
1st one @Meetjain1
