### ISSUE TITLE
Feature Update - Enhanced Notes App

### ISSUE THREAD

**Issue by atharva012004** [dhairyagothi/100_days_100_web_project#265]
**Is your feature request related to a problem? Please describe.**
Currently, it's challenging to efficiently search for specific notes and manage important ones securely within the app.

**Describe the solution you'd like**
Introduce the following features:
- **Keyword Search:** Allow users to search notes by entering keywords, enhancing accessibility to specific content.
- **Tagging System:** Implement tags for notes, enabling users to categorize and organize their notes effectively.
- **Password Protection:** Integrate a feature to secure important notes with passwords, ensuring sensitive information remains private.

**Describe alternatives you've considered**
Alternative solutions might include improving folder organization or implementing biometric authentication for security.

**Additional context**
These features will significantly improve user experience by enhancing search capabilities, organization, and security within the notes app.

video 

https://github.com/user-attachments/assets/8fb23ee9-e5fc-4b6e-abd2-dcfa93b7d57d

**Comment by dhairyagothi** [comment]
make PR @atharva012004

**Comment by atharva012004** [comment]
Done you can check now
