### ISSUE TITLE
find a bug in qr-generator project

### ISSUE THREAD

**Issue by bhagwan8815** [dhairyagothi/100_days_100_web_project#269]
**Describe the bug**
i have to find a bug in qr-generator project which is when we enter a text or link for qr-code-generator there is now result give.

**To Reproduce**

**Expected behavior**
i want to solve this bug please assign me .

**Screenshots**

https://github.com/user-attachments/assets/480c3edb-a307-4277-a585-b0fd5d28d1ec

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dhairyagothi** [comment]
good check js file @bhagwan8815
