### ISSUE TITLE
want to add Flappy-bird-project

### ISSUE THREAD

**Issue by bhagwan8815** [dhairyagothi/100_days_100_web_project#273]
hey i am bhagwan singh rana, i want to add a flappy-bird-project in your repository .
this is a funny game . the  main goal is for the bird to travel as far as it can without hitting any green pipes.
please assign me .

https://github.com/user-attachments/assets/c7aa111e-8911-4ef1-a662-9c4c47fd75e2

**Comment by dhairyagothi** [comment]
alreaady exists
