### ISSUE TITLE
Enhance BMI Calculator with Visualization, Unit Conversion, and Personalized Tips

### ISSUE THREAD

**Issue by atharva012004** [dhairyagothi/100_days_100_web_project#275]
**Is your feature request related to a problem? Please describe.**
The current BMI calculator only provides a numerical result without any visualization or context. It lacks interactive features that can help users understand their BMI trends over time and doesn't offer practical advice based on their BMI category. Additionally, entering height and weight in a single unit system can be inconvenient for users accustomed to different units.

**Describe the solution you'd like**
1. **Include Chart for BMI Data Visualization**: Add a chart to visualize BMI data over time. This will help users track their progress and understand trends in their BMI.
2. **Add Unit Conversion Options**: Provide options for inputting height and weight in different units (e.g., feet/inches, pounds). Convert these units to metric units for BMI calculation. This will make the calculator more versatile and user-friendly.
3. **Add Tips Feature**: Based on the BMI category (underweight, normal, overweight, obese), provide personalized health tips. This will offer users actionable advice to improve their health index based on their BMI.

**Describe alternatives you've considered**
1. **Static Graphs**: Instead of using Chart.js for dynamic visualization, static graphs could be generated, but this would reduce the interactivity and user engagement.
2. **Manual Unit Conversion**: Users could manually convert their height and weight to metric units, but this adds an extra step and may lead to errors.
3. **General Health Tips**: Providing general health tips regardless of BMI category, but this would not be as personalized or effective in helping users improve their health.

**Additional context**
Adding these features will not only make the BMI calculator more informative and user-friendly but also engage users with interactive and personalized content. Here are some screenshots/mockups of how the features could be integrated into the existing interface:

1. **BMI Data Visualization Chart**:
   
![Screenshot 2024-07-13 222752](https://github.com/user-attachments/assets/47a7b630-ae44-4fa3-9da8-aa205d56e88f)
   
2. **Unit Conversion Options**:
  
![Screenshot 2024-07-13 222618](https://github.com/user-attachments/assets/c30b5f88-16ad-4081-8aac-ca9fdce30f25)

3. **Personalized Health Tips**:
   
![Screenshot 2024-07-13 222648](https://github.com/user-attachments/assets/1bf734d7-d556-4873-8bd4-d1942adeb153)

**Comment by dhairyagothi** [comment]
assigned @atharva012004
