### ISSUE TITLE
Contact Book

### ISSUE THREAD

**Issue by k0msenapati** [dhairyagothi/100_days_100_web_project#276]
Build a contact management system where users can store and manage their contacts.

## Features: 
- User authentication, 
- contact CRUD operations, 
- search, and sort functionalities.

## Tech stack:
Flask, Html, Tailwind, Js

**Comment by k0msenapati** [comment]
Assign me under vsoc

**Comment by dhairyagothi** [comment]
is it backend project @kom-senapati  ?
