### ISSUE TITLE
Missionaries and Cannibals game 

### ISSUE THREAD

**Issue by AnantAgarwaL11** [dhairyagothi/100_days_100_web_project#29]
I propose adding a new project to the repository: a Missionaries and Cannibals game

**Comment by dhairyagothi** [comment]
@AnantAgarwaL11 please share a SS of what you want to add 
Also star ⭐ the repo and also update index.html after adding your project 

Assigned @AnantAgarwaL11

**Comment by AnantAgarwaL11** [comment]
![Screenshot 2024-06-17 220446](https://github.com/dhairyagothi/50_days_50_web_project/assets/115874061/36323d7a-e928-4b13-9c9e-50322ebc4c7d)
![Screenshot 2024-06-17 220425](https://github.com/dhairyagothi/50_days_50_web_project/assets/115874061/a0485715-4ec8-44e4-af21-0269d930ffba)

**Comment by AnantAgarwaL11** [comment]
Above is the screenshot of the game

**Comment by dhairyagothi** [comment]
@AnantAgarwaL11 Make A PR 
note :- First pull the main branch

**Comment by AnantAgarwaL11** [comment]
I have made a PR

**Comment by AnantAgarwaL11** [comment]
please close this issue . I have completed it .
