### ISSUE TITLE
Addition of login and signup page

### ISSUE THREAD

**Issue by Aaryanb45** [dhairyagothi/100_days_100_web_project#294]
addition of images and video

**Comment by dhairyagothi** [comment]
Good issue @Aaryanb45

**Comment by Aaryanb45** [comment]
https://github.com/user-attachments/assets/22d3b4e7-6ae6-4cba-8616-03a1dfb6c3e2

**Comment by Aaryanb45** [comment]
just have a look and review itt

**Comment by dhairyagothi** [comment]
ui not looks good but add for now we will change it in later PRs
