### ISSUE TITLE
Fixing Pre loader of website 

### ISSUE THREAD

**Issue by dhairyagothi** [dhairyagothi/100_days_100_web_project#3]
**Describe the bug**
Pre loader is not aligned to page and it's size is big need to be fixed 

**To Reproduce**

**Expected behavior**
Fixed pre loader 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by deepak-d-r4113** [comment]
Hello, I would like to contribute to this particular issue can you assign me this issue.

**Comment by dhairyagothi** [comment]
> Hello, I would like to contribute to this particular issue can you assign me this issue.

Go for it @deepak-d-r4113 assigned 

Make sure to star ⭐ the repo and add video of changes made 

Good luck

**Comment by dhairyagothi** [comment]
@deepak-d-r4113 what's the update ?

**Comment by dhairyagothi** [comment]
Opened

**Comment by Ayushswirlon** [comment]
I am interested in contributing to this issue plz assign it to me

**Comment by dhairyagothi** [comment]
> I am interested in contributing to this issue plz assign it to me

Assigned do it ASAP

**Comment by dhairyagothi** [comment]
@Ayushswirlon Add video of your changes

**Comment by Ayushswirlon** [comment]
had just started working will give you report in an hour

**Comment by dhairyagothi** [comment]
okay

**Comment by Ayushswirlon** [comment]
fixed 

https://github.com/dhairyagothi/50_days_50_web_project/assets/136717301/ed41121c-3884-4e93-abff-aaa75edba057

**Comment by dhairyagothi** [comment]
Make a PR @Ayushswirlon
