### ISSUE TITLE
Feature Enhancement : QR Generator

### ISSUE THREAD

**Issue by atharva012004** [dhairyagothi/100_days_100_web_project#307]
**Is your feature request related to a problem? Please describe.**
The basic QR generator lacks advanced customization and features, limiting its usability and visual appeal.

**Describe the solution you'd like**
I'd like the QR generator to be enhanced with the following features:
- **Improved UI:**
  - Allow users to change QR code colors.
  - Provide options for different QR code shapes (rounded corners, dots, etc.).
  - Let users add a logo or image to the center of the QR code.
- **Advanced Features:**
  - Implement error correction level selection (L, M, Q, H).
  - Add support for generating different types of QR codes (URL, text, WiFi, vCard, etc.).
  - Include a QR code scanner feature to read and decode QR codes.

**Describe alternatives you've considered**
An alternative could be using third-party QR code generators, but they often lack the level of customization and advanced features needed for specific use cases.

**Additional context**
These enhancements will make the QR generator more versatile and user-friendly, catering to a broader audience with diverse needs. Below are some screenshots illustrating the desired features and UI improvements:

Before
![Screenshot 2024-07-17 160134](https://github.com/user-attachments/assets/90725637-0349-44df-945f-d99344ba6fc0)

**Comment by atharva012004** [comment]
This is my final Vsoc24 issue, and it was a pleasure to contribute to your repository. 🙌

**Comment by atharva012004** [comment]
This is my final Vsoc24 issue, and it was a pleasure to contribute to your repository.

**Comment by dhairyagothi** [comment]
> This is my final Vsoc24 issue, and it was a pleasure to contribute to your repository. 🙌

thanku for your contributions @atharva012004
