### ISSUE TITLE
 Flappy Bird game implementation using HTML, CSS, and JavaScript with basic physics (30th mini-project)

### ISSUE THREAD

**Issue by Yaser-123** [dhairyagothi/100_days_100_web_project#31]
- Created game structure with HTML
- Styled components with CSS
- Implemented game mechanics and logic in JavaScript
  - Added bird character with jump functionality
  - Included moving pipes as obstacles
  - Developed collision detection
  - Implemented scoring system
- Integrated gravity and bird movement physics
- Added game over and restart functionality

https://github.com/dhairyagothi/50_days_50_web_project/assets/140265777/28657e6a-9f94-43e3-98de-8a3e86d1d06f

**Comment by dhairyagothi** [comment]
Assigned @Yaser-123 
make sure to add correct Day first Pull the changes 

Level of PR is assigned after checking it 
Go Ahead
