### ISSUE TITLE
Styling in main page

### ISSUE THREAD

**Issue by k0msenapati** [dhairyagothi/100_days_100_web_project#32]
**Describe the issue**
The main page is not looking good, can use better fonts and table to show the projects.

**Screenshots**
![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/92045934/8cf6f645-ec05-4e37-ad02-c11ea9d923fc)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version 125.0.2535.92

**Additional context**
I can correct the style

**Comment by dhairyagothi** [comment]
Ya go for it make a PR doing changes according to You i will see it 
Assigned @kom-senapati

**Comment by dhairyagothi** [comment]
ccompleted by #46
