### ISSUE TITLE
Adding greeting message to repo on creating a issue and merging a PR 

### ISSUE THREAD

**Issue by dhairyagothi** [dhairyagothi/100_days_100_web_project#4]
**Is your feature request related to a problem? Please describe.**
Greeting message is not working properly 

**Describe the solution you'd like**
Fixing documentation 

**Describe alternatives you've considered**

**Additional context**

**Comment by Prashant-2024** [comment]
Hey, I would like to work on this now.
i can make it quickly.

**Comment by 1754riya** [comment]
@dhairyagothi Hey, I would like to work on this issue.

**Comment by dhairyagothi** [comment]
> @dhairyagothi Hey, I would like to work on this issue.

Good Assigned @1754riya

**Comment by dhairyagothi** [comment]
Completed
