### ISSUE TITLE
Add GitHub Profile Finder as a Project 

### ISSUE THREAD

**Issue by Kaustav2410** [dhairyagothi/100_days_100_web_project#40]
We should add a new project named "GitHub Profile Finder" to our repository. This project will allow users to search for GitHub profiles and display relevant information about the profiles using the GitHub API. It will be built using React.js.

Features:

Search Functionality:

An input field to enter a GitHub username.
A button to trigger the search.
Profile Information Display:

Avatar
Username
Bio
Number of repositories
Number of followers
Number of following
Link to the GitHub profile

Error Handling:

Display a user-friendly message if the username is not found.

Styling:

Basic styling to make the app user-friendly and visually appealing.
Responsive design to ensure usability on different devices.

Technical Requirements:

Use React.js for building the user interface.
Axios to make HTTP requests to the GitHub API.
React state and lifecycle methods/hooks to manage component state and side effects.
Tailwind for styling.

**Comment by dhairyagothi** [comment]
Go Ahead assigned @Kaustav2410

**Comment by dhairyagothi** [comment]
completed
