### ISSUE TITLE
chore: implement repo basics

### ISSUE THREAD

**Issue by externref** [dhairyagothi/100_days_100_web_project#41]
The repository is missing a `.gitignore` config due toh which the `node_modules` folder is being commited to github ( which is not a good practise ). 
The LICENSE is also missing, github provides multiple LICENSE templates depending on your project needs, might want to look into it. 

Please assign me this issue if you want me to make these changes.

**Comment by dhairyagothi** [comment]
yaaa go ahead Assigned @externref

**Comment by externref** [comment]
on it, what LICENSE should i add? most open source projects use MIT.
