### ISSUE TITLE
Scoreboard for Tic Tac Toe Game

### ISSUE THREAD

**Issue by atharva012004** [dhairyagothi/100_days_100_web_project#44]
Feature Request: Scoreboard for Tic Tac Toe Game

Is your feature request related to a problem? Please describe.

The current Tic Tac Toe game lacks a scoreboard to track wins and losses for each player. This can make it difficult to see who is winning overall and doesn't provide a sense of accomplishment or competition.

Describe the solution you'd like

I'd like to add a scoreboard to the Tic Tac Toe game. This scoreboard should display:

Player 1 Wins: [Number]
Player 2 Wins: [Number]
Ties: [Number]
The scoreboard should update automatically after each game. Wins should be awarded based on the standard Tic Tac Toe win conditions. A tie should be declared if the board is filled and no player has achieved a winning line.

Please assign me this task I'm eager to contribute on this project.

**Comment by dhairyagothi** [comment]
Assigned Go ahead @atharva012004 
before Starting PUSH the MAIN branch

**Comment by dhairyagothi** [comment]
completed #53
