### ISSUE TITLE
Add Jarvis Voice Assistant

### ISSUE THREAD

**Issue by Yaser-123** [dhairyagothi/100_days_100_web_project#48]
The voice assistant accurately recognizes and processes voice commands.
Audio responses are clear, natural-sounding, and relevant to the user’s queries.
The assistant can perform a set of predefined tasks based on recognized commands.
The feature is thoroughly tested and documented.

**Comment by dhairyagothi** [comment]
Create issue as a feature issue 
First complete previous PR then do this 
PULL the MAIN branch 
Assigned @Yaser-123
