### ISSUE TITLE
To add Contribution.md file 

### ISSUE THREAD

**Issue by dhairyagothi** [dhairyagothi/100_days_100_web_project#5]
Update CONTRIBUTION.md file in repo

**Comment by Prashant-2024** [comment]
I would like to work on this issue, can you please assign it to me

**Comment by dhairyagothi** [comment]
go ahead @Prashant-2024 assigned

**Comment by dhairyagothi** [comment]
@Prashant-2024 do it fast

**Comment by deepesh611** [comment]
I can work on this

**Comment by dhairyagothi** [comment]
> I can work on this

Completed find some new issue
