### ISSUE TITLE
project: webpage with meta tags

### ISSUE THREAD

**Issue by externref** [dhairyagothi/100_days_100_web_project#51]
Several websites like Twitter and Discord use meta tags to provide useful insights of the website like title, description and name. This embed for example:

![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/70657005/4d516068-74f1-42f2-90ce-09af697fcf2f)

please assign me the issue if you want me to add an example project about it here.

**Comment by dhairyagothi** [comment]
ya ya it will increase SEO of website go ahead assigned @externref

**Comment by externref** [comment]
( to use in the header )

![](https://github.com/dhairyagothi/50_days_50_web_project/assets/70657005/002ef8e0-79f9-4d5f-8e48-9cdf20743c54)
