### ISSUE TITLE
Meet Our Team

### ISSUE THREAD

**Issue by Yaser-123** [dhairyagothi/100_days_100_web_project#56]
Explore the faces and stories behind our success. Meet the talented individuals who make up our diverse team, each contributing their unique skills and perspectives.

 Stay tuned as we add profiles with images and details of each contributor, showcasing their expertise and dedication to excellence.

**Comment by dhairyagothi** [comment]
what do you want to add ?

**Comment by Yaser-123** [comment]
bro i want to add every contributors details like this
![Uploading Screenshot 2024-06-18 120537.png…]()

**Comment by dhairyagothi** [comment]
@Yaser-123 ss is not visible

**Comment by k0msenapati** [comment]
I guess he want to add contributor avatars and names

**Comment by dhairyagothi** [comment]
check issue #52
