### ISSUE TITLE
E-Commerce website with Simple Cart Functionality using html,css and js

### ISSUE THREAD

**Issue by shravn-10** [dhairyagothi/100_days_100_web_project#59]
Propose adding a new project to teach beginners on how to implement Simple cart functionalities in an E-commerce website such as add,delete etc.

**Comment by dhairyagothi** [comment]
Go ahead @shravn-10 

assigned 
Star the repo before working on it

**Comment by k0msenapati** [comment]
Are you working @shravn-10

**Comment by shravn-10** [comment]
Yes I am almost done with it 
Will be done by today 
My exams just got over 
By today night ill be done

**Comment by shravn-10** [comment]
Interface and functionality is ready , need to add images and comments 
Will finish by end of today

**Comment by shravn-10** [comment]
Please close this issue , since the pull request was accepted
or should i only close the issue?
