### ISSUE TITLE
Adding a AI powered chatbot as 24th project

### ISSUE THREAD

**Issue by Yaser-123** [dhairyagothi/100_days_100_web_project#6]
Using gemini API for creating a chatbot for this site

**Comment by Yaser-123** [comment]
Adding 24th project

**Comment by dhairyagothi** [comment]
Assigned @Yaser-123 go for it 

Make sure to add videos and screenshot of your changes 

Best of luck

**Comment by dhairyagothi** [comment]
solved by #8

**Comment by dhairyagothi** [comment]
completed
