### ISSUE TITLE
Analog Clock using HTML , CSS and JS

### ISSUE THREAD

**Issue by AnantAgarwaL11** [dhairyagothi/100_days_100_web_project#64]
Adding an Analog clock as a project which uses HTML , CSS and js

**Comment by dhairyagothi** [comment]
@AnantAgarwaL11 share a example SS 

don't make like this already there 
![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/142989448/727754e0-aaae-467d-93b5-66e519101060)

assigned @AnantAgarwaL11

**Comment by MonishRaman** [comment]
Sir can I work on this? if yes please assign me

**Comment by AnantAgarwaL11** [comment]
![Screenshot 2024-06-18 204012](https://github.com/dhairyagothi/50_days_50_web_project/assets/115874061/5018befb-1513-42f1-bae5-f75b2a1b45a7)
Is it okay ?

**Comment by dhairyagothi** [comment]
> ![Screenshot 2024-06-18 204012](https://private-user-images.githubusercontent.com/115874061/340731389-5018befb-1513-42f1-bae5-f75b2a1b45a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MjczNDYsIm5iZiI6MTcxODcyNzA0NiwicGF0aCI6Ii8xMTU4NzQwNjEvMzQwNzMxMzg5LTUwMThiZWZiLTE1MTMtNDJmMS1iYWU1LWY3NWIyYTFiNDVhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQxNjEwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzUzOTFmZTYxMGIxNTVmNmI3OTUxNzVhMzIyMjkyMzE5ZTM4NDUxMDc2YjQ3YWQwNzYyMmViNDY2MDdmMDkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vxjp9vFn2Oh9hLTnWwUEhPWmXwP3BG70AzZi7Cac73Q) Is it okay ?

if possible make it more attractive Go ahead @AnantAgarwaL11
