### ISSUE TITLE
Calculator with Vanilla JavaScript

### ISSUE THREAD

**Issue by Yaser-123** [dhairyagothi/100_days_100_web_project#65]
Create a fully functional calculator using just HTML, CSS, and JavaScript. This project will guide you through building a simple yet effective calculator that performs basic arithmetic operations. With a clean interface and intuitive design, our calculator is a perfect example of how to leverage the power of vanilla JavaScript for interactive web applications. Follow along to enhance your coding skills and understand the core concepts behind building dynamic user interfaces

**Comment by dhairyagothi** [comment]
Don't create multiple issues once previous PR is made then start working on it 

Assigned for now 
@Yaser-123
