### ISSUE TITLE
Creating a weather Forcasting application as 25th Project

### ISSUE THREAD

**Issue by MonishRaman** [dhairyagothi/100_days_100_web_project#7]
Using HTML,CSS,Js and online Weather api that tracks the weather of a particular place once we enter the name of the place

**Comment by dhairyagothi** [comment]
Keep in mind from next time that you give a proper discription regarding issue you are making edit it now itself if possible 

Assigned @MonishRaman  Go ahead 

Make sure to add screenshot and Videos Of changes made by your PR 

Good luck

**Comment by MonishRaman** [comment]
https://github.com/dhairyagothi/50_days_50_web_project/assets/140420819/46cc17ec-0cb5-4d54-8a28-78789f2d01c2

**Comment by MonishRaman** [comment]
[All in one( Weather App).zip](https://github.com/user-attachments/files/15862775/All.in.one.Weather.App.zip)

**Comment by dhairyagothi** [comment]
@MonishRaman bro add the code of the website in repo 

Make a new folder named weather forecasting app and in that add all files and update index.html and readme.md 

And make a PR by doing changes 

Have you understand ?

**Comment by dhairyagothi** [comment]
@MonishRaman COMPLETE IT

**Comment by MonishRaman** [comment]
this project is done bro. please check once

**Comment by dhairyagothi** [comment]
> this project is done bro. please check once

You have not made any Pull Request
