### ISSUE TITLE
Scroll Game Dark Run

### ISSUE THREAD

**Issue by Yaser-123** [dhairyagothi/100_days_100_web_project#74]
Project Description
This Dark Run

 is a side-scrolling platformer where the player controls a hero navigating through obstacles to reach a finish line. The game features running, jumping, and avoiding collisions, with controls for both desktop (keyboard) and mobile (touch gestures).

Project Features
Character Control:

Hero can run left/right and jump.
Supports touch and keyboard controls.
Scrolling Environment:

Horizontally scrolling game world.
Dynamic positioning of obstacles, bushes, floors, and objects.
Collision Detection:

Detects collisions between hero and obstacles.
Ends the game upon collision.
Challenges and Difficulties
Responsive Controls:

Balancing touch and keyboard controls for smooth gameplay.
Ensuring responsive and intuitive controls on all devices.
Animation and State Management:

Managing different hero states (idle, running, jumping).
Coordinating animations with player actions.
Collision Detection:

Accurate detection of collisions between moving objects.
Handling edge cases to avoid false positives/negatives.
Scrolling Performance:

Maintaining smooth scrolling performance.
Optimizing for both desktop and mobile devices.
Timer and Scoring System:

Implementing a reliable timer for tracking game duration.
Managing high scores and displaying them correctly.
Dynamic Environment:

Creating a continuously challenging path.
Implementing dynamic obstacles with varying behaviors.
Game Over and Win Conditions:

Clearly defining and handling game over and win states.
Providing visual feedback and resetting the game appropriately.

https://github.com/dhairyagothi/50_days_50_web_project/assets/140265777/05aa949a-ed43-4750-b902-e4e73e49e867

**Comment by dhairyagothi** [comment]
Assigned @Yaser-123
