### ISSUE TITLE
TO_DO_LIST

### ISSUE THREAD

**Issue by Shivakumarjagadam** [dhairyagothi/100_days_100_web_project#80]
**Describe the bug**
The https://50-days-50-web-project.vercel.app/TO_DO_LIST/todolist.html web page is not looking good, and the task label and (got this!) button are not looking good. Some changes have to be made.

**To Reproduce**
1. Go to https://50-days-50-web-project.vercel.app/TO_DO_LIST/todolist.html
3. Scroll down
4. See the error where the input label and this button are not looking effective.

**Expected behavior**
input label & got_this! button should be in the center,, and some background color should be made in both input_label and button.

**Desktop (please complete the following information):**
 OS:windows
 Browser [e.g., Chrome, Safari]

**Comment by dhairyagothi** [comment]
okay do changes and share SS with PR dont make a new project 
Assigned @Shivakumarjagadam

**Comment by dhairyagothi** [comment]
closed
