### ISSUE TITLE
Building a  Ball Bat Stump-Game using Html,Css, Javascript. 

### ISSUE THREAD

**Issue by Shivakumarjagadam** [dhairyagothi/100_days_100_web_project#81]
### Project Description
The Ball Bat Stump Game is a simple yet engaging web-based game inspired by the classic rock-paper-scissors concept, but with a cricket twist. Developed using HTML, CSS, and JavaScript, this game allows users to play against the computer by selecting one of three cricket items: bat, ball, or stumps. The computer randomly chooses one of the remaining items, and the game determines the winner based on predefined rules.

### Game Rules
1. **Bat defeats Ball**: If the user chooses Bat and the computer chooses Ball, the user wins.
2. **Ball defeats Stumps**: If the user chooses Ball and the computer chooses Stumps, the user wins.
3. **Stumps defeat Bat**: If the user chooses Stumps and the computer chooses Bat, the user wins.
4. **Tie**: If both the user and the computer choose the same item, the result is a tie.

### How It Works
1. **User Interaction**: The user selects one of the three items (Bat, Ball, or Stumps) by clicking the corresponding button.
2. **Computer Choice**: The computer randomly selects one of the items.
3. **Result Display**: The game compares the user's choice with the computer's choice and displays the result (win, lose, or tie).
4. **Score Update**: The game keeps track of the user's wins, losses, and ties, updating the score after each round.
5. **Reset Option**: A reset button is provided to restart the game and reset the scores.

### Features
- **Interactive UI**: The game features an intuitive and visually appealing user interface.
- **Real-Time Feedback**: Immediate feedback on the user's and computer's choices and the game result.
- **Score Tracking**: The game maintains and displays a running tally of the user's wins, losses, and ties.

### Technologies Used
- **HTML**: Structure of the game and elements.
- **CSS**: Styling for an attractive and user-friendly interface.
- **JavaScript**: Game logic, user interaction handling, and result computation.

### How to Play
1. Open the game in your web browser.
2. Click on one of the items (Bat, Ball, or Stumps) to make your choice.
3. The computer will automatically choose an item.
4. View the result displayed on the screen.
5. Check the updated score.
6. Click "Reset" to start a new game round.

![Screenshot 2024-06-19 000853](https://github.com/dhairyagothi/50_days_50_web_project/assets/154302898/571da69a-38af-48cd-81c2-c35d3c9b57d6)

**Comment by dhairyagothi** [comment]
Sounds good Go ahead @Shivakumarjagadam

**Comment by Shivakumarjagadam** [comment]
I successfully added a cricket game. Please check here #152
