### ISSUE TITLE
Black Jack Game using HTML,CSS,JS

### ISSUE THREAD

**Issue by MonishRaman** [dhairyagothi/100_days_100_web_project#82]
Blackjack game

The player has to get a hand with a value as close to 21 as possible without going over. A hand that goes over 21 is a bust. The players in a blackjack game plays against the dealer. Each player has to beat the dealer's hand in order to win.

In the blackjack game, the suits have no meaning.
1. Number cards have a value equal to their number.
2. All the picture cards (Jacks, Queens, and Kings) are worth 10.
3. Aces are worth 1.

![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/140420819/815adfb6-c828-48ae-92ec-025db6ba71ce)

**Comment by dhairyagothi** [comment]
Go ahead @MonishRaman but complette previous issue first 
increase height of cards

**Comment by MonishRaman** [comment]
Uploading Black Jack - Personal - Microsoft_ Edge 2024-06-19 22-06-52.mp4…

**Comment by MonishRaman** [comment]
https://github.com/dhairyagothi/50_days_50_web_project/assets/140420819/bd4a02d8-b7de-4e92-8c83-670cd39737e8



is this fine
