### ISSUE TITLE
Card Matching Game

### ISSUE THREAD

**Issue by atharva012004** [dhairyagothi/100_days_100_web_project#86]
Welcome to the Card Matching Game! This game challenges users to find matching pairs of cards. With six pairs to find, it's a fun and engaging way to test your memory skills.

How to Play
Start the game by clicking on any card.
Click on another card to find its match.
If the cards match, they will stay flipped.
If the cards do not match, they will flip back over.
Continue until all pairs are matched.
Find all six pairs to win the game!

I am excited to share with you a card matching game that I have developed and would love to have it added to your repository. This game challenges users to find matching pairs of cards, providing an engaging and interactive experience. The project is built using JavaScript and CSS, which handle the game logic and styling respectively. JavaScript is used to shuffle cards, manage game states, and handle interactions, while CSS provides a visually appealing layout and smooth animations. I believe this addition will enhance our project by offering a fun and educational tool for users. I look forward to your feedback and hope for a positive consideration.

https://github.com/dhairyagothi/50_days_50_web_project/assets/136626840/0c2c8c2c-80f8-42e8-a944-9467d6cc9213

**Comment by dhairyagothi** [comment]
already there @atharva012004 

is there anything different from 
#20

**Comment by atharva012004** [comment]
Ya it's same and far more better I've few more things to post if you are agree i can raise issue

**Comment by dhairyagothi** [comment]
> Ya it's same and far more better I've few more things to post if you are agree i can raise issue 
>  

Do one thing make a new issue to add more things in previous existing files only

**Comment by atharva012004** [comment]
sure

**Comment by dhairyagothi** [comment]
@atharva012004 make new issue cclosing this one
