### ISSUE TITLE
In the To-do list:


### ISSUE THREAD

**Issue by kshandilaya** [dhairyagothi/100_days_100_web_project#87]
https://50-days-50-web-project.vercel.app/TO_DO_LIST/todolist.html

Once a task marked done can't be undo , if made by mistake then user will have to create a new task all over again 

I suggest to add an undo option that helps the user to unmark or undo the action.
You can also use checkboxes for the purpose and I can do that.

Will you assign me I'll make the task of checkboxes and will design accordance to your page .

**Comment by dhairyagothi** [comment]
find some different issue start with easy one
 #80 duplicate issue
