### ISSUE TITLE
UI of To-Do list :

### ISSUE THREAD

**Issue by kshandilaya** [dhairyagothi/100_days_100_web_project#89]
The appearance of https://50-days-50-web-project.vercel.app/TO_DO_LIST/todolist.html 
Is less appealing, should make it more appealing.

Can me made more appealing (such as adding light font color to the title as the background is dark colour) also alignment of the input to the center.

If you're aknowledging my suggestion then please assign me to do the changes.

**Comment by dhairyagothi** [comment]
find something new issue #80 already assigned
