### ISSUE TITLE
Contact Us Form with Google Sheets Backend Using HTML, CSS, and JavaScript

### ISSUE THREAD

**Issue by Yaser-123** [dhairyagothi/100_days_100_web_project#90]
Objective:
Develop a "Contact Us" form for a website that uses Google Sheets as the backend for storing submitted form data. The form should be built using HTML, CSS, and JavaScript.

Frontend Development::
1.HTML
2.CSS
3.JS

Google Sheets as Backend:
Set up a Google Sheet to store the submitted contact form data.
Use Google Sheets API to enable communication between the web form and the Google Sheet.
Ensure secure access to the Google Sheets API, handling authentication and authorization properly.

Resources:

Google Sheets API Documentation
Google API Client Libraries
Tutorials on AJAX/Fetch API, HTML, CSS, and JavaScript.

https://github.com/dhairyagothi/50_days_50_web_project/assets/140265777/8a61b1a0-62eb-4c9b-8e68-bcb807e1a880

**Comment by dhairyagothi** [comment]
See later on
