### ISSUE TITLE
Making the Landing page UI attractive

### ISSUE THREAD

**Issue by Khanishsuresh** [dhairyagothi/100_days_100_web_project#92]
By changing the UI of the landing page, The users would feel good about surfing through all the demo projects 

Like this even the landing page would be nice as the projects

![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/136162512/ed1f6359-476f-4101-86a2-fab0d67d046a)

**Comment by Khanishsuresh** [comment]
Hii @dhairyagothi ,

I would like to work on this issue
Would u please assign me this issue under VSOC'24

**Comment by dhairyagothi** [comment]
ya Go ahead @Khanishsuresh try to add it in box frame

**Comment by Khanishsuresh** [comment]
@dhairyagothi Okay

**Comment by dhairyagothi** [comment]
completed no response @Khanishsuresh
