### ISSUE TITLE
Adding a favicon to the webpage

### ISSUE THREAD

**Issue by Khanishsuresh** [dhairyagothi/100_days_100_web_project#93]
Adding a relative favicon to the website

![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/136162512/df6f7eea-6677-48b4-8475-729ae215e237)

**Comment by Khanishsuresh** [comment]
Hii @dhairyagothi ,

I would like to contribute to this issue
Would u please assign me to this issue under VSOC'24

**Comment by dhairyagothi** [comment]
make something related to web @Khanishsuresh

**Comment by dhairyagothi** [comment]
@Khanishsuresh  updates
