### ISSUE TITLE
adding on features to notes app

### ISSUE THREAD

**Issue by devil-90** [dhairyagothi/100_days_100_web_project#95]
**Is your feature request related to a problem? Please describe.**

**The notes app is working fine and looks nice but it has no features at all. it only takes input from the user and displays it. its just like sticky notes.**

**Describe the solution you'd like**

**we can add new features like:-**
==> rich text editor(bold, italics, underline)
==> option to add images, links and attachments
==> folder structure to organize their notes
==> setting remainders for specific notes
==> adding check-box options

**Describe alternatives you've considered**

==> integration with calender/task manager

**Additional context**

**Comment by dhairyagothi** [comment]
GOOD go AHEAD @devil-90

**Comment by dhairyagothi** [comment]
@devil-90 updates

**Comment by devil-90** [comment]
Hello @dhairyagothi I was busy this week as I had exams so I couldn't concentrate on Vsoc contributions. Please don't mind, I will update you by Monday.

**Comment by dhairyagothi** [comment]
okay np

**Comment by dhairyagothi** [comment]
not done
