### ISSUE TITLE
Enhanced Digital Clock with Multiple Designs, Time Zones, and Set Alarm feature 

### ISSUE THREAD

**Issue by atharva012004** [dhairyagothi/100_days_100_web_project#98]
Is your feature request related to a problem? Please describe.
The original digital clock application was functional but lacked variety in design and flexibility in displaying different time zones. Users were limited to a single design and could only view the local time. This limitation was frustrating for users who desired a more personalized and versatile experience, especially those who need to keep track of multiple time zones for work or personal reasons.

Describe the solution you'd like
The updated digital clock repository now includes three different designs for the digital clock, enhancing the visual experience for users. Additionally, it supports four different time zones, allowing users to easily switch between them. This update provides a more user-friendly and customizable interface, improving the overall usability and appeal of the application.

Key Features:
Three Different Designs: Users can choose from three distinct designs for the digital clock, catering to different aesthetic preferences and enhancing the visual appeal.
Four Time Zones: Users can view the current time in four different time zones, making it easier for those who need to track time across various regions.
Enhanced User Experience: The combination of multiple designs and time zones offers a more personalized and versatile experience, catering to a broader range of user needs.
Describe alternatives you've considered
Before implementing this update, several alternatives were considered:

Single Design with Color Customization: Instead of multiple designs, allowing users to customize the color scheme of a single design was considered. However, this option lacked the variety and distinctiveness provided by completely different designs.
Manual Time Zone Calculation: Providing users with a tool to manually calculate the time difference for different time zones was another option. This, however, was less user-friendly and required more effort from the users.
Browser-Based Time Zone Conversion Tools: Relying on external browser-based tools for time zone conversion was also considered, but integrating this functionality directly into the clock application offers a more seamless and efficient user experience.

Additional context
This feature update aims to significantly improve the user experience by offering more customization options and practical functionality. Below are screenshots demonstrating the new designs and time zone selection interface:

https://github.com/dhairyagothi/50_days_50_web_project/assets/136626840/1cbef4f8-ef7b-4fd8-b6ba-a0f1764eb82b

These enhancements make the digital clock more appealing and useful, especially for users who need to keep track of multiple time zones or prefer different visual styles for their clock.

**Comment by dhairyagothi** [comment]
okay make a PR 
@atharva012004 
And make PR only in given format while making PR

**Comment by atharva012004** [comment]
I have one request pls check the previous design and current upgrade so if you can please assign it in the medium category
thanks
![Screenshot 2024-06-19 164445](https://github.com/dhairyagothi/50_days_50_web_project/assets/136626840/46954173-de1c-452d-ac44-5f0b269f0f9a)
before
![Screenshot 2024-06-19 164457](https://github.com/dhairyagothi/50_days_50_web_project/assets/136626840/dcd5d4f3-b198-4e99-a8c5-dcc2907be41d)
After

**Comment by atharva012004** [comment]
Added Set Alarm feature also in the Digital Clock

https://github.com/dhairyagothi/50_days_50_web_project/assets/136626840/a1f5f1ca-4c3c-408e-a0bb-1788d0add9c2
